#    Converts data from a ls -lar into a timeline format
#    Copyright (C) 2014 Chapin Bryce
#	   You can find more code at github.com/chapinb
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

import csv
import argparse

__author__ = 'cbryce'
__version__ = 20141004

parser = argparse.ArgumentParser(description="Convert file listing output into CSV timeline. **Ensure input file was "
                                             "generated by running `ls -laR` against the desired partition**",
                                 epilog="Copyright (C) 2014 Chapin Bryce", version=__version__)
parser.add_argument('source', help="text file to process")
parser.add_argument('target', help="output csv file")

args = parser.parse_args()

fin = open(args.source)
outfile = csv.writer(open(args.target, mode='wb'))
outfile.writerow(["Permissions", "Owner", "Group", "Size", "Date", "Time", "Entry_Name", "Entry_Path"])

dir_name = ""
csv_dict = []

for line in fin:
    items = []
    if line == "\r\n":
        pass
    elif line.endswith(":\r\n"):
        dir_name = line.strip(":\r\n")
    elif line.startswith("-"):
        tmp_items = line.split(" ")
        for thing in tmp_items:
            if thing:
                things = thing.strip("\r\n")
                items.append(things)
        items.append(dir_name)
        csv_dict.append(items)

outfile.writerows(csv_dict)
